# -*- coding: utf-8 -*-
"""24-09-02-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfD2WyGcRyUGN-P5vLGtc1wFA-mw1hGU
"""

print("Hello World")

